export const CHAT_EMOJIS = [
  {key: '😀', value: 'Rosto sorridente'},
  {key: '😃', value: 'Rosto sorridente com olhos grandes'},
  {key: '😄', value: 'Rosto sorridente com olhos sorridentes'},
  {key: '😁', value: 'Rosto radiante com olhos sorridentes'},
  {key: '😆', value: 'Rosto sorridente e semicerrado'},
  {key: '😅', value: 'Rosto sorridente com suor'},
  {key: '🤣', value: 'Rolando no chão de tanto rir'},
  {key: '😂', value: 'Cara com Lágrimas de Alegria'},
  {key: '🙂', value: 'Rosto levemente sorridente'},
  {key: '🙃', value: 'Rosto Invertido'},
  {key: '🫠', value: 'Rosto Derretido'},
  {key: '😉', value: 'Cara piscando'},
  {key: '😊', value: 'Rosto sorridente com olhos sorridentes'},
  {key: '😇', value: 'Rosto Sorridente com Halo'},
  {key: '🥰', value: 'Rosto Sorridente com Corações'},
  {key: '😍', value: 'Rosto sorridente com olhos de coração'},
  {key: '🤩', value: 'Estrelado'},
  {key: '😘', value: 'Rosto Mandando um Beijo'},
  {key: '😗', value: 'Cara de Beijo'},
  {key: '😚', value: 'Beijando o rosto com os olhos fechados'},
  {key: '😙', value: 'Beijando rosto com olhos sorridentes'},
  {key: '🥲', value: 'Rosto sorridente com lágrima'},
  {key: '🧐', value: 'Rosto com Monóculo'},
  {key: '😕', value: 'Rosto Confuso'},
  {key: '🫤', value: 'Rosto com boca diagonal'},
  {key: '😟', value: 'Cara Preocupada'},
  {key: '🙁', value: 'Rosto levemente carrancudo'},
  {key: '😮', value: 'Rosto com Boca Aberta'},
  {key: '😯', value: 'Rosto Silencioso'},
  {key: '😲', value: 'Cara de espanto'},
  {key: '😳', value: 'Rosto Corado'},
  {key: '😦', value: 'Carrancudo com a boca aberta'},
  {key: '😧', value: 'Rosto Angustiado'},
  {key: '😨', value: 'Cara de medo'},
  {key: '😰', value: 'Rosto ansioso com suor'},
  {key: '😥', value: 'Rosto triste, mas aliviado'},
  {key: '😢', value: 'Cara de choro'},
  {key: '😭', value: 'Rosto de choro alto'},
  {key: '👋', value: 'Acenando com a mão'},
  {key: '🤚', value: 'Costas da mão levantadas'},
  {key: '🖐️', value: 'Mão com os dedos abertos'},
  {key: '✋', value: 'Mão levantada'},
  {key: '🖖', value: 'Saudação Vulcana'},
  {key: '🫱', value: 'Mão Direita'},
  {key: '🫲', value: 'Mão Esquerda'},
  {key: '🫳', value: 'Mão palmada para baixo'},
  {key: '🫴', value: 'Palma da mão para cima'},
  {key: '👌', value: 'Mão OK'},
  {key: '🤌', value: 'Dedos Apertados'},
  {key: '🤏', value: 'Mão apertada'},
  {key: '🤞', value: 'Dedos cruzados'},
  {key: '🫰', value: 'Mão com dedo indicador e polegar cruzado'},
  {key: '🤟', value: 'Gesto de Te Amar'},
  {key: '🤘', value: 'Signo dos Chifres'},
  {key: '🤙', value: 'Me Chame de Mão'},
  {key: '👈', value: 'Índice de backhand apontando para a esquerda'},
  {key: '👉', value: 'Índice de backhand apontando para a direita'},
  {key: '👆', value: 'Índice de backhand apontando para cima'},
  {key: '🖕', value: 'Dedo do meio'},
  {key: '👇', value: 'Backhand Index apontando para baixo'},
  {key: '🫵', value: 'Índice apontando para o visualizador'},
  {key: '👍', value: 'polegares para cima'},
  {key: '👎', value: 'Polegares para baixo'},
  {key: '✊', value: 'Punho Erguido'},
  {key: '👊', value: 'Punho que se aproxima'},
  {key: '🤛', value: 'Punho voltado para a esquerda'},
  {key: '🤜', value: 'Punho voltado para a direita'},
  {key: '👏', value: 'Mãos batendo palmas'},
  {key: '🙌', value: 'Levantando as Mãos'},
  {key: '🫶', value: 'Mãos do Coração'},
  {key: '👐', value: 'Mãos Abertas'},
  {key: '🤲', value: 'Palmas para cima juntas'},
  {key: '🤝', value: 'Aperto de mão'},
]
